---
title: "HW3"
author: "Neal Marquez"
date: "October 16, 2017"
output: pdf_document
---

# Question 1

$$
\begin{aligned}
P(X_{n+1} = X_{n} - 1 | X_n) = \frac{X_n(1-p)}{N} \\
P(X_{n+1} = X_{n} + 1 | X_n) = \frac{p(N-X_n)}{N} \\
P(X_{n+1} = X_n | X_n) = \frac{N - pN - X_n + 2pX_n}{N}
\end{aligned}
$$

$$
\begin{bmatrix}
   1-p & p & \dots & \dots & 0 \\
   \frac{1-p}{N} & \frac{N-pN-1+2p}{N} & \dots & \dots & 0 \\
   \vdots & \vdots & \ddots & \dots & 0 \\
   \vdots & \vdots & \vdots & \frac{pN - 2p + 1}{N} & \frac{p}{N} \\
   0 & 0 & 0 & 1-p & p
\end{bmatrix} 
$$

# Question 2a

```{r}
set.seed(123)
M <- 20
N <- 10
i <- 3
p <- .29

run_gamblers_ruin <- function(M, N, i, p, quietly=TRUE){
  i_start <- as.integer(rep(i, M))
  chain <- lapply(i_start, function(x) x)

  for(j in 1:M){
    end_pos <- chain[[j]]
    if(!quietly){
      cat(paste0("Starting chain number: ", j, "\n"))
    }
    while(end_pos != 0 & end_pos != N){
      if(!quietly){
        cat(paste0(end_pos, "\n"))
      }
      result <- rbinom(1, 1, prob=p)
      action <- 1^result *  (-1)^(1 - result)
      chain[[j]] <- c(chain[[j]], end_pos + action)
      end_pos <- chain[[j]][length(chain[[j]])]
    }
  }
  
  return(chain)
}

run_gamblers_ruin(M, N, i, p)
```

# Question 2b

```{r}
set.seed(123)
M <- 1000000
i <- 4
N <- 10

system.time(end_results <- sapply(seq(.1, .9, by=.1), function(p_)
  sapply(run_gamblers_ruin(M, N, i, p_), function(x) x[length(x)] == N)))

summary(end_results)

png(filename = "./GRuinSim.png")
plot(seq(.1, .9, .1), colMeans(end_results), "l", 
     xlab = "Probability of Fortune", ylab="h(4,p)",
     main="Probability of Succesful Gambler")  
dev.off()
```

# Question 3

If state $a$ is the scenario where the rat is in room 2 and the cat is in room 
1, state $b$ is the scenario where the rat is in room 1 and the cat is in room 
2, and state $x$ is the scenario where both animals are in the same room we may
rewrite the transition matrix as.

$$
\begin{bmatrix} 
.03 & .63 & .34 \\ 
.54 & .04 & .42 \\
0 & 0 & 0 \\
\end{bmatrix} 
$$

It then follows that...

$$
\begin{aligned}
m(x) & = 0 \\
m(a) & = 1 + .03m(a) + .63m(b) \\
m(b) & = 1 + .54m(a) + .04m(b) \\
m(b) & = \frac{1 + .54m(a)}{.96} \\
m(a) & = 1 + .03m(a) + .63 \Big{(} \frac{1 + .54m(a)}{.96} \Big{)} \\
m(a) & = 2.690355
\end{aligned}
$$

```{r}
M <- 1000
trans <- matrix(c(.03, .63, .34, .54, .04, .42, 0, 0, 0), 3, 3, byrow=T)
state <- sapply(1:M, function(x) c(1, 0, 0)) 
rownames(trans) <- c("{2,1}", "{1,2}", "end")
colnames(trans) <- c("{2,1}", "{1,2}", "end")

print(trans)

for(i in 1:(M-1)){
  state_i <- state[,i]
  state[,i+1] <- c(state_i %*% trans)
}

death_prob <- 0:(M-1) * state[3,]
print(sum(death_prob))
```

```{r}
alpha_ <- .7
beta_ <- .5
gamma_ <- .35

trans_shot <- matrix(c((1-alpha_)*(1-beta_)*(1-gamma_), 
         0, 
         (1-alpha_) * ((1-beta_)*gamma_ + beta_*(1-gamma_) + beta_*gamma_),
         alpha_ * (1-beta_)*(1-gamma_),
         0, 
         0, 
         alpha_ * ((1-beta_)*gamma_ + beta_*(1-gamma_) + beta_*gamma_),
         rep(0, 7),
         0, 0, (1-beta_)*(1-gamma_), 0, 0, (beta_)*(1-gamma_), (1-beta_)*(gamma_),
         0, 0, 0, (1-alpha_)*(1-gamma_), (alpha_)*(1-gamma_), 0, (1-alpha_)*(gamma_),
         0, 0, 0, 0, 1, 0, 0,
         0, 0, 0, 0, 0, 1, 0,
         0, 0, 0, 0, 0, 0, 1
         ), 7, 7, T)

rownames(trans_shot) <- c("{A,B,C}", "{A,B}", "{B,C}", "{A,C}", "{A}", "{B}", "{C}")
colnames(trans_shot) <- c("{A,B,C}", "{A,B}", "{B,C}", "{A,C}", "{A}", "{B}", "{C}")
est_probs <- (c(1, 0, 0, 0, 0, 0, 0) %*% (trans_shot %^% 100))[1,]
alpha_calc <- (alpha_**2 * (1-beta_) * (1-gamma_)**2) / 
  ((1 - (1-alpha_)*(1-gamma_))*(1-(1-alpha_)*(1-beta_)*(1-gamma_)))
all.equal(c(`{A}`=alpha_calc), c(est_probs["{A}"]))
beta_calc <- ((beta_*(1-gamma_)*(1-alpha_))*(gamma_+beta_-beta_*gamma_)) / 
  ((1-(1-gamma_)*(1-beta_))*(1-(1-gamma_)*(1-beta_)*(1-alpha_)))
all.equal(c(`{B}`=beta_calc), c(est_probs["{B}"]))
```

All non listed values are treated as 0.  

For $A$

$$
\begin{aligned}
b_A &= 1 \\
b_{A,C} &= b_{A,C}(1-\alpha)(1-\gamma) + \alpha(1-\gamma) \\
b_{A,B,C} &= b_{A,B,C}(1-\alpha)(1-\beta)(1-\gamma) + 
 b_{A,C} \alpha(1-\beta)(1-\gamma) \\
b_{A,B,C} &= \frac{\alpha^2(1-\beta)(1-\gamma)^2}
  {(1-(1-\alpha)(1-\gamma))(1-(1-\alpha)(1-\beta)(1-\gamma))}
\end{aligned}
$$

for $B$

$$
\begin{aligned}
b_B &= 1 \\
b_{B,C} &= b_{B,C}(1-\beta)(1-\gamma) + \beta(1-\gamma) \\
b_{A,B,C} &= b_{A,B,C}(1-\alpha)(1-\beta)(1-\gamma) + 
 b_{B,C} (1-\alpha)(\gamma + \beta - \beta \gamma) \\
b_{A,B,C} &=\frac{(\beta(1-\gamma)(1-\alpha))(\gamma+\beta-\beta \gamma)}
  {(1-(1-\beta)(1-\gamma))(1-(1-\alpha)(1-\beta)(1-\gamma))}
\end{aligned}
$$

for $C$

$$
\begin{aligned}
b_{C} &= 1 \\
b_{B,C} &= b_{B,C}(1-\beta)(1-\gamma) + \gamma(1-\beta) \\
b_{A,C} &= b_{A,C}(1-\alpha)(1-\gamma) + \gamma(1-\alpha) \\
b_{A,B,C} &= b_{A,B,C}(1-\alpha)(1-\beta)(1-\gamma) + 
  b_{A,C} \alpha (1-\beta)(1-\gamma) + \\
  & ~~~~~ b_{B,C}(1-\alpha)(\gamma + \beta + \beta\gamma) + 
  \alpha(\gamma + \beta + \beta\gamma) \\
b_{A,B,C} &=\frac{\frac{\alpha\gamma(1-\alpha)(1-\beta)(1-\gamma)}{1-(1-\alpha)(1-\gamma)}
  + \frac{\gamma(1-\alpha)(1-\beta)(\gamma+\beta-\beta\gamma)}{1-(1-\beta)(1-\gamma)}
  + \alpha(\gamma+\beta-\beta\gamma)}{1-(1-\alpha)(1-\beta)(1-\gamma)}
\end{aligned}
$$